# Generated by Django 2.0 on 2018-12-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('question_id', models.IntegerField()),
                ('lesson_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='tabquiz.Question'),
        ),
    ]
