# Generated by Django 2.1.4 on 2018-12-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default=None, upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='starting_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabquiz.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='step',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='tabquiz.Question'),
        ),
    ]
