# Generated by Django 2.1.4 on 2019-01-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choices', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='choice text'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_choice', to='tabquiz.Question', verbose_name='next question'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='lesson id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='text'),
        ),
    ]
