# Generated by Django 2.0 on 2018-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabquiz', '0002_auto_20181212_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
