# Generated by Django 2.1.4 on 2019-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabquiz', '0002_auto_20190103_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='final question'),
        ),
    ]
